### ISSUE TITLE
哥 多号跑的话 咋整呢

### ISSUE THREAD

**Issue by piqihaha** [lushdog/nexus-docker#1]
哥 多号跑的话 咋整呢

**Comment by lushdog** [comment]
docker-compose.yml里添加多个service

```

name: nexusxyz

services:
  nexus:
    image: trancelife/nexus:latest
    restart: unless-stopped
    network_mode: 'host'
    volumes:
      - ./.nexus:/root/.nexus
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 2048m
 nexus-2:
    image: trancelife/nexus:latest
    restart: unless-stopped
    network_mode: 'host'
    volumes:
      - ./.nexus2:/root/.nexus
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 2048m
  nexus-3:
    image: trancelife/nexus:latest
    restart: unless-stopped
    network_mode: 'host'
    volumes:
      - ./.nexus3:/root/.nexus
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 2048m
```
